version: "3.8"

services:
  backend:
    container_name: hazy_backend
    build: .
    ports:
      - 5000:8000
      - 5556:5555
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
    env_file:
      - .env
    volumes:
      - .:/app
      - pip-cache:/root/.cache/pip
    restart: always
    depends_on:
      - celerybackend

  celerybackend:
    image: redis:latest
    container_name: hazy_redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 512M
        reservations:
          cpus: 1
          memory: 256M

volumes:
  pip-cache:
    name: pip-cache
